[package]
name = "url_crawler"
version = "0.1.0"
authors = ["m3tam3re"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
reqwest = { version = "0.11", features = ["blocking"] }
